package com.glebb.osxsmartfolder.tests

class Fixtures {
	static def savedSearchWithOneScopePath = '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CompatibleVersion</key>
	<integer>1</integer>
	<key>RawQuery</key>
	<string>(((kMDItemDisplayName = ".avi*"cdw))) &amp;&amp; (true)</string>
	<key>RawQueryDict</key>
	<dict>
		<key>FinderFilesOnly</key>
		<true/>
		<key>RawQuery</key>
		<string>(((kMDItemDisplayName = ".avi*"cdw))) &amp;&amp; (true)</string>
		<key>SearchScopes</key>
		<array>
			<string>/Users/antti/Movies</string>
		</array>
		<key>UserFilesOnly</key>
		<true/>
	</dict>
	<key>SearchCriteria</key>
	<dict>
		<key>CurrentFolderPath</key>
		<array>
			<string>/Users/antti/Movies</string>
		</array>
		<key>FXCriteriaSlices</key>
		<array>
			<dict>
				<key>criteria</key>
				<array>
					<string>kMDItemDisplayName</string>
					<integer>120</integer>
					<integer>104</integer>
				</array>
				<key>displayValues</key>
				<array>
					<string>Nimi</string>
					<string>matches</string>
					<string>.avi</string>
				</array>
				<key>rowType</key>
				<integer>0</integer>
				<key>subrows</key>
				<array/>
			</dict>
		</array>
		<key>FXScope</key>
		<integer>1396925286</integer>
		<key>FXScopeArrayOfPaths</key>
		<array>
			<string>/Users/antti/Movies</string>
		</array>
	</dict>
	<key>SuggestedAttributes</key>
	<array/>
	<key>ViewSettings</key>
	<dict>
		<key>WindowState</key>
		<dict>
			<key>ShowPathbar</key>
			<true/>
			<key>ShowSidebar</key>
			<true/>
			<key>ShowStatusBar</key>
			<false/>
			<key>ShowToolbar</key>
			<true/>
			<key>SidebarWidth</key>
			<integer>192</integer>
			<key>WindowBounds</key>
			<string>{{371, 246}, {770, 440}}</string>
		</dict>
	</dict>
</dict>
</plist>
'''
	
static def savedSearchWithMultipleScopePaths = '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CompatibleVersion</key>
	<integer>1</integer>
	<key>RawQuery</key>
	<string>(((kMDItemDisplayName = ".avi*"cdw))) &amp;&amp; (true)</string>
	<key>RawQueryDict</key>
	<dict>
		<key>FinderFilesOnly</key>
		<true/>
		<key>RawQuery</key>
		<string>(((kMDItemDisplayName = ".avi*"cdw))) &amp;&amp; (true)</string>
		<key>SearchScopes</key>
		<array>
			<string>/Users/antti/Movies</string>
			<string>/Users/antti/clips</string>
		</array>
		<key>UserFilesOnly</key>
		<true/>
	</dict>
	<key>SearchCriteria</key>
	<dict>
		<key>CurrentFolderPath</key>
		<array>
			<string>/Users/antti/Movies</string>
		</array>
		<key>FXCriteriaSlices</key>
		<array>
			<dict>
				<key>criteria</key>
				<array>
					<string>kMDItemDisplayName</string>
					<integer>120</integer>
					<integer>104</integer>
				</array>
				<key>displayValues</key>
				<array>
					<string>Nimi</string>
					<string>matches</string>
					<string>.avi</string>
				</array>
				<key>rowType</key>
				<integer>0</integer>
				<key>subrows</key>
				<array/>
			</dict>
		</array>
		<key>FXScope</key>
		<integer>1396925286</integer>
		<key>FXScopeArrayOfPaths</key>
		<array>
			<string>/Users/antti/Movies</string>
			<string>/Users/antti/clips</string>
		</array>
	</dict>
	<key>SuggestedAttributes</key>
	<array/>
	<key>ViewSettings</key>
	<dict>
		<key>WindowState</key>
		<dict>
			<key>ShowPathbar</key>
			<true/>
			<key>ShowSidebar</key>
			<true/>
			<key>ShowStatusBar</key>
			<false/>
			<key>ShowToolbar</key>
			<true/>
			<key>SidebarWidth</key>
			<integer>192</integer>
			<key>WindowBounds</key>
			<string>{{371, 246}, {770, 440}}</string>
		</dict>
	</dict>
</dict>
</plist>
'''

static def savedSearchQueryScopeComputer = '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CompatibleVersion</key>
	<integer>1</integer>
	<key>RawQuery</key>
	<string>(((_kMDItemGroupId = 7) &amp;&amp; (kMDItemDisplayName = "*mkv"cd))) &amp;&amp; (true)</string>
	<key>RawQueryDict</key>
	<dict>
		<key>FinderFilesOnly</key>
		<true/>
		<key>RawQuery</key>
		<string>(((_kMDItemGroupId = 7) &amp;&amp; (kMDItemDisplayName = "*mkv"cd))) &amp;&amp; (true)</string>
		<key>SearchScopes</key>
		<array>
			<string>kMDQueryScopeComputer</string>
		</array>
		<key>UserFilesOnly</key>
		<true/>
	</dict>
	<key>SearchCriteria</key>
	<dict>
		<key>FXCriteriaSlices</key>
		<array>
			<dict>
				<key>criteria</key>
				<array>
					<string>kMDItemKind</string>
					<integer>300</integer>
					<integer>415</integer>
				</array>
				<key>displayValues</key>
				<array>
					<string>Kind</string>
					<string>is</string>
					<string>movies</string>
				</array>
				<key>rowType</key>
				<integer>0</integer>
				<key>subrows</key>
				<array/>
			</dict>
			<dict>
				<key>criteria</key>
				<array>
					<string>kMDItemDisplayName</string>
					<integer>102</integer>
					<integer>104</integer>
				</array>
				<key>displayValues</key>
				<array>
					<string>Nimi</string>
					<string>ends with</string>
					<string>mkv</string>
				</array>
				<key>rowType</key>
				<integer>0</integer>
				<key>subrows</key>
				<array/>
			</dict>
		</array>
		<key>FXScope</key>
		<integer>1396929382</integer>
		<key>FXScopeArrayOfPaths</key>
		<array>
			<string>kMDQueryScopeComputer</string>
		</array>
	</dict>
	<key>SuggestedAttributes</key>
	<array/>
	<key>ViewSettings</key>
	<dict>
		<key>WindowState</key>
		<dict>
			<key>ShowPathbar</key>
			<true/>
			<key>ShowSidebar</key>
			<true/>
			<key>ShowStatusBar</key>
			<false/>
			<key>ShowToolbar</key>
			<true/>
			<key>SidebarWidth</key>
			<integer>192</integer>
			<key>WindowBounds</key>
			<string>{{258, 289}, {770, 440}}</string>
		</dict>
	</dict>
</dict>
</plist>
'''
	static def savedSearchIssue3 = '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CompatibleVersion</key>
	<integer>1</integer>
	<key>RawQuery</key>
	<string>((InRange(kMDItemContentCreationDate,$time.today(-3d),$time.today(+1d)) &amp;&amp; (_kMDItemGroupId = 7))) &amp;&amp; (true)</string>
	<key>RawQueryDict</key>
	<dict>
		<key>FinderFilesOnly</key>
		<true/>
		<key>RawQuery</key>
		<string>((InRange(kMDItemContentCreationDate,$time.today(-3d),$time.today(+1d)) &amp;&amp; (_kMDItemGroupId = 7))) &amp;&amp; (true)</string>
		<key>SearchScopes</key>
		<array>
			<string>kMDQueryScopeComputer</string>
		</array>
		<key>UserFilesOnly</key>
		<true/>
	</dict>
	<key>SearchCriteria</key>
	<dict>
		<key>FXCriteriaSlices</key>
		<array>
			<dict>
				<key>criteria</key>
				<array>
					<string>kMDItemContentCreationDate</string>
					<integer>800</integer>
					<integer>801</integer>
					<integer>900</integer>
					<integer>901</integer>
				</array>
				<key>displayValues</key>
				<array>
					<string>Created date</string>
					<string>is</string>
					<string>within last</string>
					<string>3</string>
					<string>days</string>
				</array>
				<key>rowType</key>
				<integer>0</integer>
				<key>subrows</key>
				<array/>
			</dict>
			<dict>
				<key>criteria</key>
				<array>
					<string>kMDItemKind</string>
					<integer>300</integer>
					<integer>415</integer>
				</array>
				<key>displayValues</key>
				<array>
					<string>Kind</string>
					<string>is</string>
					<string>movies</string>
				</array>
				<key>rowType</key>
				<integer>0</integer>
				<key>subrows</key>
				<array/>
			</dict>
		</array>
		<key>FXScope</key>
		<integer>1396929382</integer>
		<key>FXScopeArrayOfPaths</key>
		<array>
			<string>kMDQueryScopeComputer</string>
		</array>
	</dict>
	<key>SuggestedAttributes</key>
	<array/>
	<key>ViewSettings</key>
	<dict>
		<key>ExtendedListViewSettings</key>
		<dict>
			<key>calculateAllSizes</key>
			<false/>
			<key>columns</key>
			<array>
				<dict>
					<key>ascending</key>
					<true/>
					<key>identifier</key>
					<string>name</string>
					<key>visible</key>
					<true/>
					<key>width</key>
					<integer>520</integer>
				</dict>
				<dict>
					<key>ascending</key>
					<false/>
					<key>identifier</key>
					<string>dateModified</string>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>181</integer>
				</dict>
				<dict>
					<key>ascending</key>
					<false/>
					<key>identifier</key>
					<string>dateCreated</string>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>181</integer>
				</dict>
				<dict>
					<key>ascending</key>
					<false/>
					<key>identifier</key>
					<string>size</string>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>97</integer>
				</dict>
				<dict>
					<key>ascending</key>
					<true/>
					<key>identifier</key>
					<string>kind</string>
					<key>visible</key>
					<true/>
					<key>width</key>
					<integer>115</integer>
				</dict>
				<dict>
					<key>ascending</key>
					<false/>
					<key>identifier</key>
					<string>dateLastOpened</string>
					<key>visible</key>
					<true/>
					<key>width</key>
					<integer>200</integer>
				</dict>
				<dict>
					<key>ascending</key>
					<true/>
					<key>identifier</key>
					<string>label</string>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>100</integer>
				</dict>
				<dict>
					<key>ascending</key>
					<true/>
					<key>identifier</key>
					<string>version</string>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>75</integer>
				</dict>
				<dict>
					<key>ascending</key>
					<true/>
					<key>identifier</key>
					<string>comments</string>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>300</integer>
				</dict>
				<dict>
					<key>ascending</key>
					<false/>
					<key>identifier</key>
					<string>dateAdded</string>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>181</integer>
				</dict>
			</array>
			<key>iconSize</key>
			<real>16</real>
			<key>showIconPreview</key>
			<true/>
			<key>sortColumn</key>
			<string>name</string>
			<key>textSize</key>
			<real>12</real>
			<key>useRelativeDates</key>
			<true/>
			<key>viewOptionsVersion</key>
			<integer>0</integer>
		</dict>
		<key>ListViewSettings</key>
		<dict>
			<key>calculateAllSizes</key>
			<false/>
			<key>columns</key>
			<dict>
				<key>comments</key>
				<dict>
					<key>ascending</key>
					<true/>
					<key>index</key>
					<integer>8</integer>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>300</integer>
				</dict>
				<key>dateCreated</key>
				<dict>
					<key>ascending</key>
					<false/>
					<key>index</key>
					<integer>2</integer>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>181</integer>
				</dict>
				<key>dateLastOpened</key>
				<dict>
					<key>ascending</key>
					<false/>
					<key>index</key>
					<integer>5</integer>
					<key>visible</key>
					<true/>
					<key>width</key>
					<integer>200</integer>
				</dict>
				<key>dateModified</key>
				<dict>
					<key>ascending</key>
					<false/>
					<key>index</key>
					<integer>1</integer>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>181</integer>
				</dict>
				<key>kind</key>
				<dict>
					<key>ascending</key>
					<true/>
					<key>index</key>
					<integer>4</integer>
					<key>visible</key>
					<true/>
					<key>width</key>
					<integer>115</integer>
				</dict>
				<key>label</key>
				<dict>
					<key>ascending</key>
					<true/>
					<key>index</key>
					<integer>6</integer>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>100</integer>
				</dict>
				<key>name</key>
				<dict>
					<key>ascending</key>
					<true/>
					<key>index</key>
					<integer>0</integer>
					<key>visible</key>
					<true/>
					<key>width</key>
					<integer>520</integer>
				</dict>
				<key>size</key>
				<dict>
					<key>ascending</key>
					<false/>
					<key>index</key>
					<integer>3</integer>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>97</integer>
				</dict>
				<key>version</key>
				<dict>
					<key>ascending</key>
					<true/>
					<key>index</key>
					<integer>7</integer>
					<key>visible</key>
					<false/>
					<key>width</key>
					<integer>75</integer>
				</dict>
			</dict>
			<key>iconSize</key>
			<real>16</real>
			<key>showIconPreview</key>
			<true/>
			<key>sortColumn</key>
			<string>name</string>
			<key>textSize</key>
			<real>12</real>
			<key>useRelativeDates</key>
			<true/>
			<key>viewOptionsVersion</key>
			<integer>0</integer>
		</dict>
		<key>WindowState</key>
		<dict>
			<key>ShowPathbar</key>
			<true/>
			<key>ShowSidebar</key>
			<true/>
			<key>ShowStatusBar</key>
			<true/>
			<key>ShowToolbar</key>
			<true/>
			<key>SidebarWidth</key>
			<integer>185</integer>
			<key>WindowBounds</key>
			<string>{{103, -0}, {1084, 840}}</string>
		</dict>
	</dict>
</dict>
</plist>
'''
}
